[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NEXT_PUBLIC_API_BASE_URL = "https://cheerful-truffle-f285d5.netlify.app/api/v1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
