[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NEXT_PUBLIC_USE_MOCK_DATA = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
