export const CAROUSEL_CONFIG = {
  AUTO_PLAY_INTERVAL: 5000,
  RESUME_DELAY: 10000,
  INTERSECTION_THRESHOLD: 0.7
} as const

export const TESTIMONIAL_CONFIG = {
  AUTO_PLAY_INTERVAL: 5000,
  RESUME_DELAY: 10000
} as const
